export const teamFlags: Record<string, string> = {
  Portugal: "🇵🇹",
  England: "🏴",
  Netherlands: "🇳🇱",
  Brazil: "🇧🇷",
  Argentina: "🇦🇷",
  Japan: "🇯🇵",
  France: "🇫🇷",
  Spain: "🇪🇸",
  Germany: "🇩🇪",

  Morocco: "🇲🇦",
  Senegal: "🇸🇳",
  Croatia: "🇭🇷",
  Sweden: "🇸🇪",
  Switzerland: "🇨🇭",
  Belgium: "🇧🇪",
  Uruguay: "🇺🇾",
  Mexico: "🇲🇽",
  Canada: "🇨🇦",
  Australia: "🇦🇺",
  Turkey: "🇹🇷",
  Paraguay: "🇵🇾",
  Ecuador: "🇪🇨",
  Tunisia: "🇹🇳",
  Egypt: "🇪🇬",
  Iran: "🇮🇷",

  "New Zealand": "🇳🇿",
  Qatar: "🇶🇦",
  Scotland: "🏴",
  Haiti: "🇭🇹",

  "South Korea": "🇰🇷",
  Czechia: "🇨🇿",
  "South Africa": "🇿🇦",

  "Bosnia-Herzegovina": "🇧🇦",
  "United States": "🇺🇸",
  "Ivory Coast": "🇨🇮",
  "Saudi Arabia": "🇸🇦",

  "Congo DR": "🇨🇩",
  Curaçao: "🇨🇼",
  "Cape Verde Islands": "🇨🇻",
};